/* V6 page tracker — the data.
 *
 * This file is the source of truth. index.html only renders it.
 * Every time a page changes for V6, update that page here:
 *   - status      todo | planning | building | review | done
 *   - v6.plan     what we decided to change (one line each)
 *   - changelog   { date, note } — newest first
 * and add a line to LOG at the bottom.
 *
 * Element kinds: shell | header | section | card | list | form | action | sheet | state
 *   sheet = dialog/sheet/overlay opened from the page
 *   state = what shows instead of the content (loading, empty, error)
 */

window.V6 = {
  inventoryDate: '2026-09-26',
  branch: 'v6-organisms',
  shots: {
    date: '2026-09-19',
    mobile: '../screens/2026-09-19-mobile-390x844/',
    desktop: '../screens/2026-09-19-desktop-1440x900/',
    wide: '../screens/2026-09-19-desktop-1920x1080/',
  },

  groups: [
    { id: 'global', label: 'On every page' },
    { id: 'entry', label: 'Getting in' },
    { id: 'nav', label: 'Main navigation' },
    { id: 'swap', label: 'Swapping' },
    { id: 'account', label: 'Account & rewards' },
    { id: 'staff', label: 'Staff only' },
  ],

  pages: [
    // ─────────────────────────────── On every page
    {
      id: 'shell',
      name: 'App shell (navigation)',
      group: 'global',
      routes: ['every signed-in page'],
      split: 'mobile + desktop + tablet',
      files: [
        'src/components/shell/AppShell.tsx',
        'src/components/shell/Topbar.tsx',
        'src/components/shell/Sidebar.tsx',
        'src/components/shell/TabBar.tsx',
        'src/components/shell/MobileMenu.tsx',
        'src/components/shell/PageHeader.tsx',
        'src/components/shell/PageBody.tsx',
        'src/navigation/destinations.ts',
      ],
      shot: null,
      purpose: 'The frame around every signed-in page: top bar, desktop rail, phone tab bar and menu.',
      elements: [
        { kind: 'header', name: 'Top bar', note: 'Menu burger (phone), Bartefy wordmark, version label, brass "Add" (desktop), bell with dot, language + theme (desktop), avatar → Profile (desktop). Shrinks 68→56px on scroll.' },
        { kind: 'shell', name: 'Desktop sidebar rail', note: 'Collapse chevron; Discover, Matches, My Items; divider; Profile, Settings; Moderation + Analytics for staff. Count badges. 224px / 68px collapsed; always collapsed on tablet.' },
        { kind: 'shell', name: 'Phone tab bar', note: 'Green pill: Discover, Matches, My Items + brass "+" Add. Dot on Matches for offers/unread.' },
        { kind: 'sheet', name: 'Phone menu', note: 'Account row (email), all destinations with badges, theme toggle, language, sign out, build stamp.' },
        { kind: 'section', name: 'PageHeader / PageTabs', note: 'Shared page title + subtitle + actions + underline tabs. Used by My Items, Matches (desktop), Notifications, Profile, Settings, admin.' },
        { kind: 'section', name: 'PageBody', note: 'Shared width container (variants incl. "wide").' },
        { kind: 'state', name: 'Global extras', note: 'Update prompt bar, toasts, staff A/B badge, error boundary per route.' },
      ],
      status: 'done',
      v6: {
        plan: [
          'No search anywhere — the deck is random (Alex, 2026-09-26).',
          'Desktop: navigation lives in a left side nav (side_nav organism); the top bar keeps brand, streak chip, points chip, bell, account.',
          'Side nav collapses to a 72px icon rail; tablet always uses the rail.',
          'No prices anywhere (Alex, 2026-09-27): no Est. $, no valuation, no delta. apply-shell.mjs strips them from every Stitch page.',
          'Phone (Alex, 2026-09-27): bottom tab bar Discover · Swaps · ＋Add · Finds · You; You opens a sheet (account, Points & Tiers, Profile, Settings, language, theme, sign out). Top-bar chips open bottom sheets. Alternative: Points as the fifth tab.',
          'Side nav = Add + 4 places to go + Collapse. Account menu (desktop) and You sheet (phone) = Profile, Settings, Language, Theme, Sign out (Alex, 2026-09-27).',
          'No footer on any page (Alex, 2026-09-27) — apply-shell.mjs removes it.',
          'Colours: ONLY the 11 Brand Book colours (Alex, 2026-09-27) — brand.mjs re-points every Stitch token. Coral/Sun are fills with Ink text, never text on white.',
          'Top bar R2 (Alex, 2026-09-27): hover a chip = one-line tooltip; click = popover with the organism behind it (streak → #03, points → wallet, bell → notifications, avatar → account menu). Phone: bottom sheet.',
        ],
        notes: 'V6 grids agreed: 4 / 8 / 12 columns, desktop capped at 1600px. Design: revision R1 (stitch/02-discover-desktop-r1.html).',
      },
      changelog: [{ date: '2026-09-29', note: 'Top bar (brand lockup, page context, streak/points/bell/account), side nav (Add + 4), phone tab bar + You sheet — applied to every V6 page.' }, { date: '2026-09-27', note: 'Top bar R2: hover = tooltip, click = popover (phone: bottom sheet). Streak chip opens #03, points chip the wallet, bell the notifications, avatar the account menu (Profile · Settings · Sign out · build stamp). "+ Earn" removed. Sheet: stitch/organisms/topbar-r2.html.' }, { date: '2026-09-26', note: 'R1: search removed; nav moved from the top bar into a new left side nav (organism #02 side_nav). Top bar now: brand · streak · points · bell · account.' }, { date: '2026-09-26', note: 'Stitch S1 (Discover desktop) received. It redraws the top bar: 4 nav links with status badges, streak + points chips, search. 3 open questions on the organism.' }],
    },

    // ─────────────────────────────── Getting in
    {
      id: 'auth',
      name: 'Sign in / Sign up',
      group: 'entry',
      routes: ['/', '/login', '/signup'],
      split: 'mobile + desktop',
      files: ['src/screens/Auth/Auth.mobile.tsx', 'src/screens/Auth/Auth.desktop.tsx', 'src/screens/Auth/AuthForm.tsx', 'src/screens/Auth/useAuth.ts'],
      shot: '01-auth.png',
      shotAlt: '02-signup.png',
      purpose: 'One screen, two modes. Email → 6-digit code sign-in; sign-up adds name and invite code.',
      elements: [
        { kind: 'shell', name: 'Treasure-map background', note: 'Full-bleed map image under a 93% parchment wash. No app nav.' },
        { kind: 'header', name: 'Brand header', note: 'Wordmark, language switcher, Orzomi byline.' },
        { kind: 'section', name: 'Brand panel (desktop only)', note: 'Left half, deep green: welcome title + body, animated swap illustration with drifting blobs, "always free" line.' },
        { kind: 'header', name: 'Welcome title + body', note: 'Mobile only (desktop has it in the brand panel).' },
        { kind: 'form', name: 'Email step', note: 'Title (sign in / sign up), Name field (sign-up), Email field, Invite code field with "found" check (sign-up), error line, primary button "Send code" / "Create account", switch link to the other mode.' },
        { kind: 'form', name: 'Code step', note: 'Mail icon, "code sent to <email>", 6-box OTP input (auto-submits, shakes on error), resend with countdown, "wrong email" link.' },
      ],
      status: 'done',
      v6: { plan: [], notes: '' },
      changelog: [],
    },
    {
      id: 'onboarding',
      name: 'Onboarding',
      group: 'entry',
      routes: ['/welcome'],
      split: 'mobile + desktop',
      files: ['src/screens/Onboarding/Onboarding.mobile.tsx', 'src/screens/Onboarding/Onboarding.desktop.tsx', 'src/screens/Onboarding/steps.tsx', 'src/screens/Onboarding/useOnboarding.ts'],
      shot: '03-onboarding.png',
      purpose: 'Four steps after first sign-in: intro, city, tastes, finish.',
      elements: [
        { kind: 'section', name: 'Brand panel (desktop only)', note: 'Green panel over the map: wordmark, welcome title, tagline, "always free" line.' },
        { kind: 'header', name: 'Step header', note: 'Back arrow, FlowSteps progress dots, Skip. Language switcher on desktop.' },
        { kind: 'section', name: 'Step 1 — Intro', note: 'Body + three icon points (list a find / hunt / swap).' },
        { kind: 'section', name: 'Step 2 — City', note: 'Body + city chips (single select).' },
        { kind: 'section', name: 'Step 3 — Tastes', note: 'Body + info hint + category chips with icons (multi select).' },
        { kind: 'section', name: 'Step 4 — Finish', note: 'Sparkles icon, body, "always free" card.' },
        { kind: 'action', name: 'Footer actions', note: 'Next (disabled until valid); last step: "List my first find" (→ /add) and "Start hunting" (→ /discover).' },
      ],
      status: 'done',
      v6: { plan: [], notes: '' },
      changelog: [],
    },

    // ─────────────────────────────── Main navigation
    {
      id: 'discover',
      name: 'Discover (the deck)',
      group: 'nav',
      routes: ['/discover'],
      split: 'mobile + desktop',
      files: ['src/screens/Hunt/Hunt.mobile.tsx', 'src/screens/Hunt/Hunt.desktop.tsx', 'src/screens/Hunt/useHunt.ts', 'src/components/hunt/HuntStack.tsx', 'src/components/hunt/HuntCard.tsx', 'src/components/hunt/ActionButtons.tsx', 'src/components/hunt/WatchPrompt.tsx'],
      shot: '04-discover.png',
      purpose: 'Swipe nearby finds. Want = send an offer, pass, super offer, undo, boost your own.',
      stitch: ['S1'],
      elements: [
        { kind: 'header', name: 'Page title', note: 'Desktop only ("Discover").' },
        { kind: 'card', name: 'Hunt card stack', note: 'Photo carousel with prev/next + dots, condition badge, "eyeing" count, expand-photos button, title, category badge, description with more/less, owner avatar + name + trust score, distance.' },
        { kind: 'action', name: 'Action buttons', note: 'Undo, Pass, Super offer, Want, Boost. Desktop shows keyboard hints.' },
        { kind: 'section', name: 'Detail side panel (desktop only)', note: 'Owner row (rating, swaps, distance, profile link), what they want, "See everything" → item page.' },
        { kind: 'state', name: 'Empty deck', note: 'Title + body with radius, "Widen to N km", "Reach further" (upgrade pitch). Watch prompt (save a search) above or below — A/B test deck_empty_cta.' },
        { kind: 'card', name: 'Next-step nudge', note: '"List your first find" when you have nothing to offer.' },
        { kind: 'sheet', name: 'Offer sheet', note: 'Pick which of your finds to offer; super and multi offers cost points; "Add a find" and "Get points" routes.' },
        { kind: 'sheet', name: 'Match celebration', note: 'Bottom sheet (phone) / dialog (desktop): title, body, SwapPair of both finds, "Say hello" → chat, "Keep hunting".' },
        { kind: 'sheet', name: 'Upgrade sheets', note: 'After an undo is blocked (just_passed) and when the stack is empty (stack_empty).' },
      ],
      status: 'done',
      v6: { plan: ['Wide card + full-width layout (2026-09-28): landscape card with the details panel beside the photo once the deck column is ≥860px; rail pinned right at 320–400px; Discover + area chip in the top bar.', 'Deck stage R1 (Alex, 2026-09-27): card + action bar always fit the window, no scrolling. Owner, wants and the match pill live on the photo; the rest behind i. Drag/keys/buttons all work.', 'Deck action bar: R1 (five equal buttons, no key legend) — see organism deck_actions.', ], notes: 'Desktop design received (Stitch S1): streak band on top, deck on 8 of 12 columns, a 4-column rail with Expiring offers, My Table and Tier meter. No phone design yet.' },
      changelog: [{ date: '2026-09-28', note: 'Wide screens (Alex, 2026-09-28: "massive empty space around cards" on a 17-inch laptop and a 22–24-inch screen). When the deck column is ≥860px the card turns landscape: photo on the left at the same size, the "i" details as an always-open white panel on the right (360px; 420px when the column is ≥1200px), the "fits" button at its foot. Narrower columns (1440 with the full nav, tablet, phone) keep the portrait card. The rail keeps a fixed width (320–400px) against the right edge; the deck column takes the rest; no 1280px cap. Top bar: "Discover" + an area chip (Silver Lake · 10 km) that opens a popover — area, distance 2/5/10 km, 25/50 locked to Collector.' }, { date: '2026-09-27', note: 'Deck stage R1: card sized to the window with the action bar under it; owner/wants on the photo; details panel; drag + keys. Right rail R1; no footer; no streak banner.' }, { date: '2026-09-26', note: 'Deck action bar R1: key legend removed; five equal buttons (Undo · Pass · Put on Table · Super · Boost); Eye dropped, Boost back; only Put on Table filled.' }, { date: '2026-09-26', note: 'Stitch S1 received and disassembled into 12 organisms (V6-Organisms tab). Nothing built yet.' }],
    },
    {
      id: 'items',
      name: 'My finds',
      group: 'nav',
      routes: ['/items'],
      split: 'single file (4 cols desktop / 2 cols phone)',
      files: ['src/screens/MyItems.tsx'],
      shot: '05-items.png',
      purpose: 'Your own finds, plus the ones you saved.',
      elements: [
        { kind: 'header', name: 'PageHeader + tabs', note: 'Title "My Items"; tabs Live / Paused / Eyeing.' },
        { kind: 'action', name: '"Choose what is live"', note: 'Ghost button, Paused tab only, opens the paused-finds sheet.' },
        { kind: 'list', name: 'Masonry photo grid', note: 'Photo (true aspect ratio) + title; "Paused" badge on paused tab. Tap → item page.' },
        { kind: 'state', name: 'Empty per tab', note: 'Live → "Add"; Eyeing → "Discover"; Paused → no action.' },
        { kind: 'sheet', name: 'Paused finds sheet', note: 'Pick which finds stay live within your tier limit.' },
      ],
      status: 'done',
      v6: { plan: ['Shell: side nav + no search (standing decisions, applied by apply-shell.mjs).'], notes: 'Desktop design received (Stitch S4 "My Finds & Inventory", R4 with the side nav): header with capacity, expiry alert, filter chips + sort, rich find cards in 4 states, stall stats, listing dialog. No phone design yet.' },
      changelog: [{ date: '2026-09-28', note: 'Proposal B: grid + detail, one screen, Hunter and 50-find versions. Renamed My finds. Waiting on Alex.' }, { date: '2026-09-26', note: 'Stitch S4 received: 6 new organisms (items_header, renewal_alert, inventory_filters, stall_card, stall_stats, listing_composer); tier_meter compact now drawn.' }],
    },
    {
      id: 'matches',
      name: 'Matches (inbox)',
      group: 'nav',
      routes: ['/matches'],
      split: 'mobile + desktop (desktop = list + thread side by side)',
      files: ['src/screens/SwapsInbox/SwapsInbox.mobile.tsx', 'src/screens/SwapsInbox/SwapsInbox.desktop.tsx', 'src/screens/SwapsInbox/SwapList.tsx', 'src/screens/SwapsInbox/OffersLink.tsx', 'src/screens/SwapsInbox/Tabs.tsx', 'src/screens/SwapsInbox/useSwapsInbox.ts'],
      shot: '07-matches.png',
      purpose: 'Every agreed swap, with unread state. Gateway to Offers and to each chat.',
      elements: [
        { kind: 'header', name: 'Title + tabs', note: '"Matches"; tabs Active / Done.' },
        { kind: 'card', name: 'Offers link', note: 'Banner row to /offers with the waiting count.' },
        { kind: 'list', name: 'Swap list', note: 'StatusRow per swap: both thumbnails, "yours ↔ theirs" line, status, unread dot. Selected row highlighted on desktop.' },
        { kind: 'card', name: '"Traded elsewhere" notice', note: 'Above a cancelled row, with Archive.' },
        { kind: 'section', name: 'Thread pane (desktop only)', note: 'Right column: the chat for the selected swap, or "pick a swap" / empty state.' },
        { kind: 'state', name: 'Empty', note: '"No swaps yet" + "Go hunting"; next-step nudge.' },
      ],
      status: 'done',
      v6: { plan: ['Shell: side nav + no search (standing decisions, applied by apply-shell.mjs).', 'Agreed swap card #15 R1 (Alex, 2026-09-27): only the agreement and the double confirmation. Both confirm → chat closes, both finds leave Bartefy. No meetup, map, chat peek or QR.'], notes: 'Desktop design received (Stitch S2 "Active Swaps & Offers", revision R2 with the side nav). It MERGES this page and Offers: header with 5 status tabs, offer cards (wide + tile), agreed-swap card with meetup spot / chat peek / handover steps, always-free pledge. No phone design yet.' },
      changelog: [{ date: '2026-09-28', note: 'Volume test: 6 offers + 14 agreed. A (as drawn) = 8,494px of page. B (proposal) = one screen, list + detail. Waiting on Alex.' }, { date: '2026-09-27', note: 'Agreed swap card R1: agreement + double confirmation only (5 states, confirm dialog, compact for the chat header, phone). Swapped into R2.' }, { date: '2026-09-26', note: 'Stitch S2 received and split into 9 new organisms (2 not recommended); top bar + footer reused from S1. R2 = S2 with the side nav.' }],
    },

    // ─────────────────────────────── Swapping
    {
      id: 'offers',
      name: 'Offers',
      group: 'swap',
      routes: ['/offers'],
      split: 'single file',
      files: ['src/screens/Offers/Offers.tsx', 'src/screens/Offers/useOffers.ts'],
      shot: '08-offers.png',
      purpose: 'Offers you received (accept / decline) and offers you sent (pending).',
      elements: [
        { kind: 'header', name: 'Title + toggle', note: '"Offers"; Incoming / Sent toggle buttons.' },
        { kind: 'list', name: 'Offer card', note: 'Sender name + trust score, expiry countdown, "Super" badge; "They want" thumb → "They offer" thumb; Accept + Decline (incoming) or "waiting" line (sent).' },
        { kind: 'card', name: 'Multi-offer group', note: 'Several offers from one person grouped under "<name> offered N finds".' },
        { kind: 'state', name: 'Empty / error', note: 'Package icon + "No offers" + "Discover".' },
      ],
      status: 'done',
      v6: { plan: [], notes: 'Organism ready on the branch: ExpiringOffersOrganism (not placed on any page yet).' },
      changelog: [{ date: '2026-09-26', note: 'Stitch S2: Offers becomes two tabs of the Active Swaps page (decision pending).' }],
    },
    {
      id: 'chat',
      name: 'Chat (swap thread)',
      group: 'swap',
      routes: ['/matches/:swapId'],
      split: 'mobile full screen / desktop inside Matches',
      files: ['src/screens/Chat/MatchThread.tsx', 'src/screens/Chat/MatchThreadPane.tsx', 'src/screens/Chat/useMatchChat.ts', 'src/components/swap/ConfirmBar.tsx', 'src/components/swap/MessageBubble.tsx'],
      shot: '18-chat.png',
      purpose: 'Talk, arrange, confirm the handover.',
      elements: [
        { kind: 'header', name: 'Thread header', note: 'Back, other person name + trust score.' },
        { kind: 'card', name: 'Swap header', note: '"Your find" → "Their find", thumbnails, tap → item page.' },
        { kind: 'list', name: 'Messages', note: 'System "accepted" bubble, text bubbles, voice-note bubbles.' },
        { kind: 'action', name: 'Confirm bar', note: 'Both sides confirm the handover.' },
        { kind: 'action', name: '"Arrange" button', note: '→ /matches/:id/arrange (map pin).' },
        { kind: 'form', name: 'Composer', note: 'Voice recorder, textarea (Enter sends), send button; error line.' },
      ],
      status: 'done',
      v6: { plan: ['Shell: side nav + no search (standing decisions, applied by apply-shell.mjs). Chat sits under Active Swaps & Offers.'], notes: 'Desktop design received (Stitch S5, R5 with the side nav). DIFFERENT design system from S1–S4 (green primary, Outfit + JetBrains Mono). Match banner + item dock, then chat list · thread · safeguards / meetup zone / trust pledge. No phone design yet.' },
      changelog: [{ date: '2026-09-29', note: 'Folded into Swaps & offers (Alex, 2026-09-28): the chat is the right side of an agreed swap; the thread list is the agreed rows.' }, { date: '2026-09-26', note: 'Stitch S5 received: 5 new organisms (match_dock, swap_thread_list, chat_thread, meetup_proposal, chat_composer); handover_steps, meetup_spot, free_pledge, owner_bar, meta_strip, footer, points_wallet, topbar get S5 versions.' }],
    },
    {
      id: 'arrange',
      name: 'Arrange meetup',
      group: 'swap',
      routes: ['/matches/:swapId/arrange'],
      split: 'single file',
      files: ['src/screens/Arrange.tsx'],
      shot: '19-arrange.png',
      purpose: 'Propose where and when to meet, or to post it.',
      elements: [
        { kind: 'header', name: 'Heading + step', note: '"Step N of M" + heading.' },
        { kind: 'form', name: 'Mode chips', note: 'Meet / Post.' },
        { kind: 'form', name: 'Place field', note: 'Meet mode only; help text.' },
        { kind: 'form', name: 'When chips', note: 'Time proposals.' },
        { kind: 'action', name: 'Propose button', note: 'Sends a proposal message into the chat; error / "need a place" line.' },
        { kind: 'card', name: 'Safety note', note: '"One tap" + safety body (meet safely is ALWAYS_FREE).' },
      ],
      status: 'done',
      v6: { plan: [], notes: '' },
      changelog: [{ date: '2026-09-29', note: 'CUT (Alex, 2026-09-27): "I do not care where they meet" — no meetup step; the chat is where people arrange it.' }, ],
    },
    {
      id: 'itemdetail',
      name: 'Item detail',
      group: 'swap',
      routes: ['/item/:itemId'],
      split: 'mobile + desktop',
      files: ['src/screens/ItemDetail/ItemDetail.mobile.tsx', 'src/screens/ItemDetail/ItemDetail.desktop.tsx', 'src/screens/ItemDetail/Facts.tsx', 'src/screens/ItemDetail/useItemDetail.ts'],
      shot: '16-itemdetail.png',
      purpose: 'One find in full — someone else\'s (offer on it) or your own (manage it).',
      elements: [
        { kind: 'header', name: 'Top row', note: 'Back, save (heart), report (flag).' },
        { kind: 'section', name: 'Photo gallery', note: 'Main photo, "photo N of M", view-all → full-screen PhotoViewer.' },
        { kind: 'section', name: 'Facts', note: 'Title, condition, category, story; owner row → profile; what they want; "reserved" note.' },
        { kind: 'action', name: 'Primary action', note: 'Theirs: "Offer a swap". Mine: Manage → Renew / Remove.' },
        { kind: 'card', name: 'Eyeing (desktop)', note: '"N people eyeing" + "See who" (upgrade moment) + info hint.' },
        { kind: 'sheet', name: 'Sheets', note: 'Offer sheet, Report sheet, Remove confirm, Upgrade sheet (desktop).' },
        { kind: 'state', name: 'Not found', note: 'Title + body + "Discover".' },
      ],
      status: 'done',
      v6: { plan: [], notes: '' },
      changelog: [{ date: '2026-09-29', note: 'CUT (Alex): the Discover card is the find — its photos open full screen from the card (⛶ or a tap in the middle). Nothing links to a find page any more.' }, { date: '2026-09-29', note: 'DONE (Alex: "Item detail - is good"). 17-item-b.html + organisms/item-phone-r1.html.' }],
    },
    {
      id: 'additem',
      name: 'Add a find',
      group: 'swap',
      routes: ['/add'],
      split: 'mobile (stepped) + desktop (one page)',
      files: ['src/screens/AddItem/AddItem.mobile.tsx', 'src/screens/AddItem/AddItem.desktop.tsx', 'src/screens/AddItem/sections.tsx', 'src/screens/AddItem/useAddItem.ts'],
      shot: '06-additem.png',
      purpose: 'List a find: photos, details, what you want in return.',
      elements: [
        { kind: 'header', name: 'Header', note: 'Phone: back + FlowSteps (3 steps). Desktop: "Put it on the table" title, sections divided by separators.' },
        { kind: 'form', name: 'Photos', note: 'PhotoWell grid, help text.' },
        { kind: 'form', name: 'Details', note: 'Title, story (optional), category chips, condition picker/slider, info hints.' },
        { kind: 'form', name: 'Wants', note: 'Wanted category chips, "anything" option, note field.' },
        { kind: 'action', name: 'Footer actions', note: 'Continue / Publish, "Not now"; publish-failed line.' },
        { kind: 'section', name: 'Published', note: 'Success: boost offer, "List another", "See my items".' },
        { kind: 'sheet', name: 'Upgrade sheet', note: 'When the live-find limit is hit (402).' },
      ],
      status: 'done',
      v6: { plan: ['Shell: side nav + no search (standing decisions, applied by apply-shell.mjs).'], notes: 'Stitch S4 lists a find from a dialog (listing_composer) instead of the /add page on desktop. No category picker in the design.' },
      changelog: [{ date: '2026-09-29', note: 'DONE (Alex: "Add a find - is good").' }, { date: '2026-09-29', note: 'Proposal B: 18-add-b.html — the app\'s real form, every ＋ opens it; published / held / table-full states; phone 3 steps.' }, { date: '2026-09-26', note: 'Stitch S4: desktop listing becomes a dialog (decision pending).' }],
    },

    {
      id: 'eyeing',
      name: 'Admirers (who put a find on the table for yours)',
      group: 'swap',
      routes: ['/admirers'],
      split: 'new page',
      files: [],
      shot: null,
      purpose: 'The quiet offers: a free Put on Table is hidden from the owner. This page shows them. Collector only.',
      elements: [
        { kind: 'header', name: 'Title + count', note: 'Who’s eyeing your finds · 99+ (counts cap at 99+ everywhere).' },
        { kind: 'list', name: 'Filter chips', note: 'All your finds / one chip per find with its count.' },
        { kind: 'list', name: 'Cards', note: 'Their find photo, “for your X”, who, when, New. Hunter: blurred + lock. Collector: Pass · Swap.' },
        { kind: 'action', name: 'Go Collector bar', note: 'Hunter only; pinned above the tab bar on a phone.' },
        { kind: 'sheet', name: 'It’s a bartefy! (match moment)', note: 'Swap → the two finds meet, confetti, Say hello · Keep hunting.' },
      ],
      status: 'done',
      v6: { plan: ['Collector only (Alex, 2026-09-29) — no points unlock.', 'Swap from a card = instant match (Alex).', 'Nav: side nav row “Eyeing · 99+ eyeing”, phone You tab badge + You sheet row.'], notes: '' },
      changelog: [{ date: '2026-09-30', note: 'Confirmed by Alex, with the match moment and the Discover phone layout.' }, { date: '2026-09-29', note: 'Renamed Admirers (Alex did not like Eyeing): 20-admirers-b.html. 1,000 TEST pts in the mock; Go Collector spends 600 and unlocks; Reset test.' }, { date: '2026-09-29', note: 'New page (locked / #collector / #collector+match).' }],
    },

    // ─────────────────────────────── Account & rewards
    {
      id: 'notifications',
      name: 'Notifications',
      group: 'account',
      routes: ['/notifications'],
      split: 'single file',
      files: ['src/screens/Notifications.tsx'],
      shot: '09-notifications.png',
      purpose: 'Reached from the bell. What happened while you were away.',
      elements: [
        { kind: 'header', name: 'PageHeader', note: '"Notifications".' },
        { kind: 'list', name: 'Feed', note: 'Icon + line per event, tap to open it.' },
        { kind: 'state', name: 'Empty', note: 'Title + body.' },
      ],
      status: 'done',
      v6: { plan: [], notes: '' },
      changelog: [],
    },
    {
      id: 'profile',
      name: 'Profile (mine)',
      group: 'account',
      routes: ['/profile'],
      split: 'single file',
      files: ['src/screens/Profile.tsx'],
      shot: '10-profile.png',
      purpose: 'You at a glance, and the way to points, invites and membership.',
      elements: [
        { kind: 'header', name: 'Identity', note: 'Avatar, name, "verified" badge, member since.' },
        { kind: 'section', name: 'Stats', note: 'Swaps, live finds, points (3 Stat tiles).' },
        { kind: 'card', name: 'Invite card', note: 'Title + body → /invite.' },
        { kind: 'card', name: 'Membership row', note: 'Tier, radius, finds limit → /membership.' },
        { kind: 'action', name: 'Sign out', note: '' },
      ],
      status: 'done',
      v6: { plan: ['Dedicated page (Alex, 2026-09-27). Doubles as the PUBLIC profile others open from "Julian’s Desk (4)": avatar, name, tier, completed swaps, member since, their finds on the table. Your own adds edit, points + streak tile, invite, membership. No V6 design yet.', ], notes: '' },
      changelog: [{ date: '2026-09-28', note: 'Proposal B built (own + public in one design), desktop + phone. Waiting on Alex.' }, { date: '2026-09-27', note: 'Decided: dedicated V6 page, doubling as the public profile others open from the owner bar. To design.' }, ],
    },
    {
      id: 'publicprofile',
      name: 'Someone else\'s profile',
      group: 'account',
      routes: ['/u/:userId'],
      split: 'single file',
      files: ['src/screens/PublicProfile.tsx'],
      shot: '17-publicprofile.png',
      purpose: 'Who you are swapping with.',
      elements: [
        { kind: 'header', name: 'Back + identity', note: 'Avatar, name, trust score.' },
        { kind: 'list', name: 'Their finds', note: 'Grid of their live finds; empty line.' },
        { kind: 'action', name: 'Block', note: 'Opens BlockSheet (ALWAYS_FREE).' },
      ],
      status: 'done',
      v6: { plan: [], notes: '' },
      changelog: [{ date: '2026-09-28', note: 'CUT as a page (Alex): no browsing other people\'s finds. Replaced by the person card — who they are and swaps done, Block. Nothing else.' }, ],
    },
    {
      id: 'points',
      name: 'Points & rewards',
      group: 'account',
      routes: ['/points'],
      split: 'single file',
      files: ['src/screens/Rewards.tsx'],
      shot: '11-points.png',
      purpose: 'The points economy: balance, streak, how to earn, what to spend on.',
      elements: [
        { kind: 'header', name: 'Back + title', note: '"Points".' },
        { kind: 'card', name: 'Balance', note: 'Current points.' },
        { kind: 'card', name: 'Streak', note: 'Day count + body.' },
        { kind: 'list', name: 'How to earn', note: 'Daily visit (range), listing (capped), other earn reasons.' },
        { kind: 'list', name: 'Spend', note: 'Tiers and perks, duration, "active" badge, buy buttons.' },
        { kind: 'list', name: 'History', note: 'Ledger of points in / out with reasons.' },
        { kind: 'section', name: 'Footnote', note: '' },
      ],
      status: 'done',
      v6: { plan: ['Shell: side nav + no search (standing decisions, applied by apply-shell.mjs).'], notes: 'Desktop design received (Stitch S3 "Points & Tiers", R3 with the side nav): balance + invite, streak tile, how to earn, tier plans, perk store, history. Folds Membership and part of Invite into this page. No phone design yet.' },
      changelog: [{ date: '2026-09-28', note: 'Proposal B: wallet + earn | Tiers · Perks · History, one screen, points only. Waiting on Alex.' }, { date: '2026-09-26', note: 'Stitch S3 received: 5 new organisms (invite_banner, earn_rules, tier_plans, perk_store, points_ledger) + streak, points_wallet, meta_strip reused.' }],
    },
    {
      id: 'invite',
      name: 'Invite friends',
      group: 'account',
      routes: ['/invite'],
      split: 'single file',
      files: ['src/screens/Invite.tsx'],
      shot: '12-invite.png',
      purpose: 'Your referral code and how many joined.',
      elements: [
        { kind: 'header', name: 'Back + title + pitch', note: '' },
        { kind: 'card', name: 'Your code', note: 'Code, Copy, Share (native share sheet).' },
        { kind: 'section', name: 'Your invites', note: 'Stat tiles: joined, traded; "when paid" note.' },
      ],
      status: 'done',
      v6: { plan: ['Shell: side nav + no search (standing decisions, applied by apply-shell.mjs).'], notes: 'Stitch S3 puts an invite_banner inside the Points balance card. The Invite page itself is not drawn.' },
      changelog: [{ date: '2026-09-29', note: 'Folded: the invite code + Copy live on Points (a friend\'s first swap) and in Profile → Only you see this.' }, { date: '2026-09-26', note: 'Stitch S3: invite banner drawn on Points; this page not redesigned yet.' }],
    },
    {
      id: 'membership',
      name: 'Membership',
      group: 'account',
      routes: ['/membership'],
      split: 'single file',
      files: ['src/screens/Membership.tsx'],
      shot: '13-membership.png',
      purpose: 'Tiers and one-off purchases. (Stripe not live — points are the currency.)',
      elements: [
        { kind: 'header', name: 'Title + headline + subhead', note: '' },
        { kind: 'list', name: 'Tier cards', note: 'Price, perks, "Most popular" and "Current" badges, Upgrade button.' },
        { kind: 'list', name: 'One-offs', note: 'Spotlight, postage.' },
        { kind: 'card', name: 'Always free', note: 'Title + body + info hint.' },
      ],
      status: 'done',
      v6: { plan: ['Shell: side nav + no search (standing decisions, applied by apply-shell.mjs).'], notes: 'Stitch S3 folds this page into Points & Tiers (tier_plans organism). Nav has no Membership entry.' },
      changelog: [{ date: '2026-09-29', note: 'Folded into Points & tiers (Tiers tab, points only). /membership becomes a redirect.' }, { date: '2026-09-26', note: 'Stitch S3: Membership becomes the "Tiers" section of Points & Tiers (decision pending).' }],
    },
    {
      id: 'settings',
      name: 'Settings',
      group: 'account',
      routes: ['/settings'],
      split: 'single file (two columns on desktop)',
      files: ['src/screens/Settings.tsx'],
      shot: '14-settings.png',
      purpose: 'Account, membership, notifications, tips, blocked people, sign out, delete.',
      elements: [
        { kind: 'header', name: 'PageHeader', note: '"Settings".' },
        { kind: 'section', name: 'Account', note: 'Language switcher, city picker.' },
        { kind: 'section', name: 'Membership', note: 'Current tier, manage → /membership, "always free" card.' },
        { kind: 'section', name: 'Notifications', note: '3 switches: match, message, email.' },
        { kind: 'section', name: 'Tips', note: 'Replay tips.' },
        { kind: 'action', name: 'Rows', note: 'Blocked people → /settings/blocked, Sign out, Delete account (confirm dialog).' },
        { kind: 'section', name: 'Footer', note: 'Orzomi byline, build stamp.' },
      ],
      status: 'done',
      v6: { plan: ['Dedicated page, ONE page with sections (Alex, 2026-09-27): Account (email, city), Notifications (3 switches), Language, Theme, Membership, Tips, Blocked people (its own sub-page, exists), Sign out, Delete account, build stamp. No V6 design yet.', ], notes: '' },
      changelog: [{ date: '2026-09-28', note: 'Proposal B built: sections | section; all at once from 1600px; phone list → section. Waiting on Alex.' }, { date: '2026-09-27', note: 'Decided: dedicated V6 page, one page with sections — not a hub of sub-pages. To design.' }, ],
    },
    {
      id: 'blocked',
      name: 'Blocked people',
      group: 'account',
      routes: ['/settings/blocked'],
      split: 'single file',
      files: ['src/screens/BlockedList.tsx'],
      shot: '15-blocked.png',
      purpose: 'Everyone you blocked, and unblock.',
      elements: [
        { kind: 'header', name: 'Back + title + body', note: '' },
        { kind: 'list', name: 'Blocked person card', note: 'Avatar, name, reason, "since", Unblock.' },
        { kind: 'sheet', name: 'Unblock confirm', note: 'AlertDialog.' },
        { kind: 'state', name: 'Empty', note: 'Shield icon + title + body.' },
      ],
      status: 'done',
      v6: { plan: [], notes: '' },
      changelog: [{ date: '2026-09-29', note: 'Folded into Settings → Privacy & blocked people (Unblock with confirm).' }, ],
    },

    // ─────────────────────────────── Staff only
    {
      id: 'reports',
      name: 'Moderation queue',
      group: 'staff',
      routes: ['/admin/reports'],
      split: 'single file (list + panes)',
      files: ['src/screens/admin/ReportQueue.tsx', 'src/screens/admin/useReportQueue.ts'],
      shot: null,
      purpose: 'Staff review reported items and users. Nothing is decided automatically.',
      elements: [
        { kind: 'header', name: 'PageHeader + tabs', note: 'Title, subtitle, report/held tabs.' },
        { kind: 'list', name: 'Report list', note: 'Status + reason badges, held-item rows.' },
        { kind: 'section', name: 'Item pane', note: 'Reported item, evidence, mark reviewing / resolved, hide / restore.' },
        { kind: 'section', name: 'Uploader pane', note: 'Avatar, trust, stats (items, joined, hidden, blocked, reports), suspend with reason / reinstate.' },
        { kind: 'state', name: 'No access / empty / pick one', note: '' },
      ],
      status: 'done',
      v6: { plan: ['Phone (2026-09-29): the queue is the page; an upload or report opens full screen with a back arrow, decisions pinned to the bottom.'], notes: 'Staff tool — probably last.' },
      changelog: [{ date: '2026-09-29', note: 'DONE (Alex: "Staff tools - is good. i do not see mobile variant") — phone added: Staff tools title + Staff only chip, queue as the page, tap → full screen with back arrow, Publish/Hide and the report decisions pinned to the bottom. Sheet: organisms/staff-phone-r1.html.' }, { date: '2026-09-29', note: 'Proposal B: 19-staff-b.html (Moderation tab) — Uploads (held/live/hidden, uploader pane, suspend) and Reports (frozen swap, evidence, internal note, unfreeze / cancel-and-relist, resolve). Nothing decided automatically. Staff reach it from the account menu.' }, ],
    },
    {
      id: 'analytics',
      name: 'Analytics & experiments',
      group: 'staff',
      routes: ['/admin/analytics'],
      split: 'single file',
      files: ['src/screens/admin/Analytics.tsx', 'src/screens/admin/useAnalytics.ts'],
      shot: null,
      purpose: 'DAU/WAU/MAU, funnel, event table, A/B experiments.',
      elements: [
        { kind: 'header', name: 'PageHeader + tabs', note: '' },
        { kind: 'section', name: 'Metric tiles', note: 'DAU, WAU, MAU, streaks + sparkline.' },
        { kind: 'section', name: 'Funnel', note: 'Bars.' },
        { kind: 'list', name: 'Activity table', note: 'Event / total / people.' },
        { kind: 'list', name: 'Experiments', note: 'Goal, split, start / stop / remove, results with verdict.' },
        { kind: 'form', name: 'New experiment', note: 'Key, goal, description, split slider.' },
      ],
      status: 'done',
      v6: { plan: [], notes: 'Staff tool — probably last.' },
      changelog: [{ date: '2026-09-29', note: 'DONE. Phone: one column; the funnel/events/experiment cards no longer run off the right edge (were min 380px wide).' }, { date: '2026-09-29', note: 'Proposal B: 19-staff-b.html (Analytics tab) — today/week/month/streak tiles, sign-up→swap funnel, events table, A/B experiments with the too-early verdict.' }, ],
    },
  ],

  /* Not pages: routes that only redirect. Kept so old links and push
   * notifications keep working. */
  redirects: [
    ['/verify', '/'],
    ['/register', '/signup'],
    ['/hunt', '/discover'],
    ['/browse', '/discover'],
    ['/swaps', '/matches'],
    ['/swaps/:id', '/matches/:id'],
    ['/chat/:id', '/matches/:id'],
    ['/cancel/:id', '/matches/:id'],
    ['/activity', '/matches'],
    ['/match/:matchId', 'Match shim → Discover'],
    ['anything else', '/'],
  ],

  /* What V6 still needs a design for, beyond the pages themselves (those are
   * computed live in index.html from sources + placements). */
  GAPS: [
    { area: 'Whole-app decisions', items: [
      ['Phone designs', 'All 5 Stitch pages are desktop only. The app is used mostly on phones (TabBar, bottom sheets) — every page needs a 390px design.'],
      ['Tablet', 'Three platforms exist (touch tablet = collapsed rail). Nothing drawn for 768–1024px.'],
      ['Dark theme', 'Dark is the app DEFAULT. No Stitch page has a dark version.'],
      ['One palette', 'S1–S4 are terracotta + Epilogue; S5 is green + Outfit/JetBrains Mono; the palette chosen on 2026-09-26 is a third set. Pick one before building.'],
      ['One nav', 'S1–S4: 4 links; S5: 5 links incl. Chat. R1 side nav settles desktop; the phone TabBar + menu are not redesigned.'],
      ['Georgian (KA)', 'No design checked with Georgian text, which runs longer and has no uppercase.'],
    ]},
    { area: 'Sheets & pop-ups (in the app, not drawn)', items: [
      ['Match celebration', '"It\'s a Bartefy!" sheet after an offer is accepted (Discover). S5 has a banner, not the moment itself.'],
      ['Upgrade sheet', 'Opened on 402 and at limits (UpgradeSheet) — tier_plans / tier_meter do not cover the sheet.'],
      ['Report a find', 'ReportItemSheet — reporting is ALWAYS_FREE and must be easy to find.'],
      ['Block someone', 'BlockSheet (Public profile). ALWAYS_FREE.'],
      ['Trouble / cancel a swap', 'TroubleSheet with reasons. S5 only shows a red "Cancel swap offer" link.'],
      ['Confirm & rate', 'ConfirmAndRateSheet — confirm handover + tags. handover_steps shows the button, not the sheet.'],
      ['Paused finds', 'PausedFindsSheet — choose which finds stay live within the tier limit.'],
      ['Phone menu', 'MobileMenu — account, destinations, theme, language, sign out.'],
      ['Photo viewer', 'Full-screen photos from Item detail and the deck card.'],
      ['Update prompt + toasts', 'UpdatePrompt bar and sonner toasts — every Stitch page draws its own toast.'],
    ]},
    { area: 'States (every page needs them)', items: [
      ['Empty states', 'Empty deck, no finds, no swaps, no offers, no notifications, nobody blocked — none drawn. Only the full, happy version of each page exists.'],
      ['Loading', 'No skeletons / loading states drawn.'],
      ['Errors & offline', 'Error, offline and "not found" (Item detail) states — none drawn. Streak has an offline state planned.'],
      ['First-time user', 'New account: 0 points, 0 finds, day 1 streak, no swaps. Every page is drawn for a busy, established user.'],
    ]},
    { area: 'Small pieces (in the app, not drawn)', items: [
      ['Voice notes', 'Recording + playback in chat (shipped). S5 has no voice button.'],
      ['Next-step nudges', 'NextStep cards ("List your first find", "Go hunting").'],
      ['Watch prompt', 'Save-what-you-want prompt on the empty deck (A/B test deck_empty_cta).'],
      ['Info hints', 'InfoHint tooltips / popovers used across forms.'],
      ['Language + city pickers', 'LanguageSwitcher, CityPicker (Settings, Onboarding).'],
      ['Staff A/B badge', 'ExperimentBadge — staff only.'],
    ]},
  ],

  /* Global log, newest first. */
  LOG: [
    { date: '2026-09-30', note: 'Alex confirmed Admirers, It’s a bartefy! (match moment) and Discover phone (C). Nothing on the review page is waiting any more.' },
    { date: '2026-09-29', note: 'Item detail CUT (Alex: “why do we need it when Discover shows everything?”) — the Discover card opens its photos full screen (⛶ button or a tap in the middle; swipe, arrows, thumbnails, Esc). Eyeing renamed ADMIRERS; the mock starts at 1,000 test pts and Go Collector really spends 600 and unlocks (Reset test). Discover phone DECIDED = C: dock at the bottom, no scroll, rail gone; top bar from the right ⋮ · Swaps (messages) · Notifications · Profile; ⋮ opens a menu: Add a find, Discover · Swaps · My finds · Admirers · Points (420), the Collector bar + streak, Needs you (2 offers expiring, My table, Hunter), Settings. Fixed: taps on the card went to the drag (pointer captured on touch-down) — now captured only once it moves.' },
    { date: '2026-09-29', note: 'Alex’s list of 9. (1–3) Item detail: no “N people saved it”, no Save for later, no Share, no Reserved or shared-link states — one action, Offer a swap. Saving removed EVERYWHERE (Alex): My finds Saved tab + save counts, the two saved-find notifications, the Points perk “See who saved your finds”. (4) Add a find: Make cover on any photo. (5) Composer: “2–4 at once · 150 pts” is now a switch card beside Super offer (one or the other). (6) Super offer in Swaps: one bolt icon, no “spent 50 pts” sentence. (7) NEW Eyeing page — quiet offers, Collector only, blurred for Hunter, Swap = match; side nav + You tab badge capped at 99+. (8) NEW match moment “It’s a bartefy!” — from Accept swap, Swap on Eyeing, and the Discover mirror match (Fender card). (9) Swaps: Archive group — swapped, chat closed, read-only.' },
    { date: '2026-09-29', note: 'Alex picked C and asked for three more versions of it: actions stay at the bottom, the card fills the rest, the page does NOT scroll; Offers expiring / My table / Hunter–Collector leave the page. C1 (Alex): icon nav + coral "2 · 4h" expiring chip in the top bar → sheet; streak, My table, tier move into You. C2: ☰ drawer (profile, Discover/Swaps/My finds/Points, Needs you, Settings); top bar ☰ · B · streak · ＋ · bell. C3: C top bar + one swipeable "needs you" line under it (card 596px vs 640px). Pages stitch/02-discover-phone-c1|c2|c3.html; sheet organisms/deck-phone-c-variants.html. Waiting on Alex to pick.' },
    { date: '2026-09-29', note: 'Discover on a phone — 3 variants (Alex: the action bar and the tab bar are two rows of five; on Discover people mostly use the actions — give them room). A on the card: no tray, buttons float on the card edge sized by use, slimmer tab bar (card 552 → 658px). B one dock: actions in the thumb zone, tabs shrink to an icon strip under them (604px). C nav goes up: tabs move into the top bar as icons, the actions own the bottom (640px). Real pages: stitch/02-discover-phone-a|b|c.html; sheet organisms/deck-phone-variants.html. Phone only; desktop and tablet unchanged. Waiting on Alex to pick.' },
    { date: '2026-09-29', note: 'Item detail, Add a find, Staff tools marked DONE (Alex) — every V6 page is now confirmed. Staff tools got its phone variant (Alex: "i do not see mobile variant"): queue as the page, tap → full screen with a back arrow, decisions pinned to the bottom; Analytics in one column. Sheet: organisms/staff-phone-r1.html, linked from 00-review.html.' },
    { date: '2026-09-29', note: 'Working alone (Alex: "do the other things without me; I\'ll confirm when all are done"): Add a find, Staff tools (Moderation + Analytics) built; Chat / Membership / Invite / Blocked closed as folded; Arrange closed as cut; one review page: stitch/00-review.html.' },
    { date: '2026-09-29', note: 'Add a find B (18-add-b.html) — every ＋ opens it now (side nav, rail, tab bar, My finds tile); Stitch\'s old dialog retired. The app\'s real form: photos (only a photo is required; cover + up to 8), name, story, categories (as many as fit), the 5 conditions (For parts · Needs work · Well loved · Good · Like new), wants = categories or Open to anything + a wish. After: It\'s on the table (+20 pts, Boost 75) or Held for a quick look. Hunter at 6/6: Your table is full (pause one / Collector). Desktop one screen (photos | form); phone 3 steps. Removed from Stitch #32: $ valuation, karma, 4 invented conditions, no category.' },
    { date: '2026-09-29', note: 'Item detail B (17-item-b.html): ONE find — where a notification, saved find, offer, chat or shared link lands; nothing leads to more of the owner\'s finds (their name opens the person card). Gallery left (arrows, thumbs, keys), facts right: condition/category, distance, saves, Listed by → person card, about, Hoping to swap for, "your X fits", report; one action: Offer a swap. States: available · reserved (sun note, offer waits) · a shared link signed out (Sign up to offer) · gone (item.notFound copy). Your OWN find opens in My finds. Phone: photos edge to edge, action pinned. Sheet: organisms/item-phone-r1.html.' },
    { date: '2026-09-29', note: 'Onboarding marked DONE (Alex: "good").' },
    { date: '2026-09-29', note: 'Onboarding B (16-onboarding-b.html): the app\'s 4 steps — welcome (3 lines; "rate each other" → "both confirm"), city (Tbilisi pre-picked, the only launch city; 10 km; area never an address), tastes (the 15 taxonomy categories, only seed the first cards), finish (List my first find · Start hunting, +20 pts). Same frame as Sign in; the green side draws each step with real finds. Phone: buttons pinned to the bottom. Sheet: organisms/onboarding-phone-r1.html. NOTE: the rest of the mock says Silver Lake, LA (Stitch data) — the app launches in Tbilisi.' },
    { date: '2026-09-29', note: 'Sign in / sign up marked DONE (Alex: "good").' },
    { date: '2026-09-29', note: 'Sign in: B | Bartefy lockup (Alex); phone strip of small photos → one green card with three finds fanned + the tagline (first screen only). ORZOMI (Alex: "made by my company, put it somewhere I can see it"): the app\'s own vector + "A product of ORZOMI" (OrzomiByline wording) at the foot of sign-in, in Settings → Help, and at the foot of the account menu.' },
    { date: '2026-09-28', note: 'Sign in / sign up B (15-signin-b.html): the app\'s passwordless flow and copy word for word — email → 6-digit code (six boxes, paste, auto-submit, wrong-code clears), sign-up = name + email + optional invite (ticks when it checks out), app error messages. Desktop: form left, a wall of real finds right with "Swap what you don\'t use." and 3 steps. Phone: wordmark, strip of finds, form. Sheet: organisms/signin-phone-r1.html.' },
    { date: '2026-09-28', note: 'Notifications marked DONE (Alex: "good, next").' },
    { date: '2026-09-28', note: 'Notifications B (14-notifications-b.html): the 8 kinds the app sends; each row = the find\'s photo + kind badge, title, one line, time, straight to where it\'s about; Today / Yesterday / Earlier; All · Unread; Mark all read; all-caught-up state. Right: Needs you now (offers ending, your turn to confirm, leaving the deck). Phone: needs-you chips + feed. The bell\'s See all links here. Sheet: organisms/notifications-phone-r1.html.' },
    { date: '2026-09-28', note: 'Profile (R2 + person card) and Settings marked DONE (Alex: "looks good" / "nicely done").' },
    { date: '2026-09-28', note: 'Settings B (13-settings-b.html): one page, 7 sections — Account (code sign-in email, area, name/photo → Profile, sign out, Delete apart), Notifications (the 3 real switches), Language (6 packs, EN is the source), Appearance (Light · Dark · Match my device), Privacy & blocked people (who sees what = the person-card rule; Unblock with confirm), Membership (→ Points & tiers), Help (replay tips, version). Desktop: sections | section; from 1600px all seven at once in three columns (1920 fits one screen). Phone: the list is the page, a section opens full screen. Delete: bottom sheet, type DELETE. Account menu + You sheet link here. Phone sheet: organisms/settings-phone-r1.html.' },
    { date: '2026-09-28', note: 'STANDING RULE (Alex): nobody browses another person\'s finds — "it violates the randomness; people will visit desks and pick items that way." Public desk page retired (12-profile-julian-b.html deleted). Tapping a name opens the PERSON CARD: photo, name, area, since, verified, swaps done, Block — no finds, no count, no past swaps. "See desk" / "Desk · 4" gone everywhere → "About Julian". Profile R2: who you are + Only you see this | How others see you (your own person card) + your finished swaps (private). No table grid, no Share your desk.' },
    { date: '2026-09-28', note: 'Profile B, no Stitch page (Alex: "you can do it"). One design, two views: your profile (12-profile-b.html) = your desk as others see it + an "Only you see this" card (tier, points, invite code); someone\'s desk (12-profile-julian-b.html) = what every "See desk" opens — no wallet, no tier. Left: photo, name, area, since, verified, swaps done (the trust number), on the table, Looking for (from the wants on their finds), "your X fits". Right: their table (max 3 across, photos grow), last swaps as photo pairs (partner hidden). Find → dialog with Offer a swap. ⋮ → Block (always free). Edit profile: photo, name, area (never an address). Account menu + phone You sheet now link to Profile; Julian\'s desk links are live. Phone sheet: organisms/profile-phone-r1.html.' },
    { date: '2026-09-28', note: 'Swaps & offers marked DONE (Alex: "swap and offers are done too, I like what you did") — proposal B: Offers + Swaps on one page, chat inside, phone. The Offers page folds into it.' },
    { date: '2026-09-28', note: 'My finds and Points & tiers marked DONE (Alex: "looks good. this is done as well"), desktop + phone.' },
    { date: '2026-09-28', note: 'Phone sheets for My finds (7 frames) and Points (4 frames): stitch/organisms/finds-phone-r1.html, points-phone-r1.html. Points on a phone: Earn becomes a 4th tab (Alex: tiers sat under five earn rows) — balance on top, Earn · Tiers · Perks · History, one at a time.' },
    { date: '2026-09-28', note: 'Points & tiers B: one screen. Left: wallet (420 pts, 180 more for Collector, +254 earned this week) + the 5 ways to earn from lib/points.ts (listing quota 4/10, the 7-day streak in its row, Copy invite link in the friend row). Right: Tiers (points only — no $, no card) · Perks (2 you turn on here for 7 days; Boost/Super/Multi spent in the moment, with where) · History (All/Earned/Spent). Phone: stacked, tier cards swipe. Cut: Protocol 027, Swap Tender, Audit ID, hashed ledger, Tier column, @handles, $ + Subscribe with Card, keyword alerts, ratings, postage. File: stitch/06-points-b.html.' },
    { date: '2026-09-28', note: 'My finds B (Alex: "My finds and Inventory are the same" → the page and the side nav are now just "My finds"). Same pattern as Swaps: photo grid + the picked find on the right, one screen. Top bar: My finds + capacity chip (6 of 6 · full). Tabs On the table · Paused · Saved; a Needs-you line (leaving soon · offers · in a swap) that jumps to the find; category chips past 12. Cards: photo + ONE badge, no buttons. Detail: big photo, the 30-day clock + Renew, offers on it (→ Swaps), its swap (→ chat), wants, saves (who = perk), one loud action per state. Phone: 2-col grid, tap → full screen. Files: stitch/08-my-finds-b.html (Hunter 6/6) and -b-50.html (Collector, 50). Cut: valuations, #codes, Counter, Auto-Renew, Trust Score, stats.' },
    { date: '2026-09-28', note: 'Swaps on phone + tablet (below 1024): the list is the page — title, offers as a swipeable strip of photo cards (soonest first, timer + Super on the photo, your find as a tiny thumb), chat rows below. Tap → full screen over the tab bar with a back arrow. Offer: their find big, yours as one row, Decline · Accept pinned. Chat: two-line swap strip (back · pair · name · ticks · ⋮, confirm full width), composer at the bottom. Confirm = bottom sheet. Sheet: stitch/organisms/swaps-phone-r1.html (8 live frames).' },
    { date: '2026-09-28', note: 'Chat moves INTO Swaps (Alex: "Chat is something the user goes back and forth to — why not have it on this page?"). Agreed swap selected → the right side is its chat: a slim swap strip on top (pair — click for big photos —, You/them ticks, the one confirm action, ⋮ desk · call it off · report), messages with voice notes, composer (send works). Agreed rows = chat rows: name, last message, unread count. Offers keep the big-photo view (no chat before accept). Proposal: the separate Chat page (R5) and #34 swap_thread_list go away.' },
    { date: '2026-09-28', note: 'Swaps B: Open chat / Read the chat → the Chat page (also in the #15 sheet); Call it off → toast (trouble sheet not designed); confirm opens the R1 dialog for that swap. Photos in the detail side grow with the window (Alex: "whenever you have space, give images more space") — 270px tall at 1407×790, 451px at 1920×971, never pushing the buttons off screen. New #15 variant: pane.' },
    { date: '2026-09-28', note: 'Active Swaps at volume (Alex: 6 expiring offers + 14 agreed — will users run away?). A = as drawn, repeated: 8,494px tall at 1407. B = proposal, one screen: grouped list (Offers to you · Your turn · Agreed · Waiting for them · Your offers) + the picked one in full on the right; the page never scrolls. stitch/04-active-swaps-volume-a.html / -b.html. handoverDesk now takes any partner + pair.' },
    { date: '2026-09-28', note: 'Discover marked DONE (Alex: "we can say that Discovery page is Fully Done"). Next: Active Swaps & Offers.' },
    { date: '2026-09-28', note: 'Deck card shadow softened (was 18px down, 40px blur, 28% — it greyed the top of the action bar; Alex). The action bar now sits above the card layer.' },
    { date: '2026-09-28', note: 'Discover on big screens: the wide card (photo + details panel), rail pinned right, no 1280px cap; top bar gets "Discover" + the area chip. Brand slot in the top bar is now as wide as the side nav so page context starts on the content edge (every page).' },
    { date: '2026-09-27', note: 'Brand Book palette + type applied to every page revision and organism sheet (v6-pages/brand.mjs): only the 11 Brand Book colours; Green = the one primary action and links; Mint + Deep Forest = selected; Paper background, white cards, Stone fills; Ink / Slate text; Coral = Add a find (Give) and urgency fills; Sun = cost badges and streak days. Outfit + Figtree. Stitch originals untouched. Chat (R5) not yet — its Stitch file uses a different token set.' },
    { date: '2026-09-27', note: 'Top bar: B | Bartefy when the side nav is expanded; the B alone when collapsed, on tablet and phone (Alex).' },
    { date: '2026-09-27', note: 'Top bar logo → the B symbol tile only (Alex). 48×48 like a collapsed nav item and in the same column when collapsed; phone 40×40.' },
    { date: '2026-09-27', note: 'Brand Book read (Alex). Top bar logo is now the real wordmark alone, Green on white (brand assets in v6-pages/brand/). The rest of the mock still uses the Stitch palette — Brand Book palette pending Alex’s go.' },
    { date: '2026-09-27', note: 'Confirmed (Alex): swipe right opens the composer; the card leaves only when the offer is sent.' },
    { date: '2026-09-27', note: 'Deck stage R1 (#06–#09, Alex: card + action bar without scrolling, swipe is the main function). Card sized from the window; owner + wants + match pill on the photo; details behind i; drag left/right, keys, photo taps; composer on swipe right. Verified to fit at 1280×720, 1440×900, 1920×1080, 390×844. Sheet X7. The Discover deck column is rebuilt and fully clickable.' },
    { date: '2026-09-27', note: 'Discover right rail R1 (Alex): Expiring offers, My table and Hunter tier as three foldable cards — one-line headers with the key number, folded state remembered, rail sticky; 565px open vs 1,204. Sheet X6. Footer deleted from every page (standing rule in apply-shell.mjs).' },
    { date: '2026-09-27', note: 'Decisions (Alex): streak banner removed from Discover — the top-bar chip is the streak. Profile, Settings, Language, Theme leave the side nav → account menu only (same list as the phone You sheet). Profile and Settings get dedicated V6 pages (to design).' },
    { date: '2026-09-27', note: 'Phone navigation R1 (new organism tab_bar): tab bar Discover · Swaps · ＋Add · Finds · You, You sheet, phone top bar with bottom sheets, phone deck bar + offer sheet — built into every page revision, testable at 390px. Alternative with Points as the fifth tab (?tabs=points). Sheet X5 frames the real pages.' },
    { date: '2026-09-27', note: 'Side nav #02 made clickable (Alex: no redesign, make it testable). Links between the 5 page revisions, Collapse/Expand remembered across pages, rail tooltips, tablet = rail, Add a find → listing form, language menu, toasts for pages with no V6 design. Top bar links wired too (brand → Discover, popovers → Points & Tiers, notifications → Swaps/Chat).' },
    { date: '2026-09-27', note: 'Offer composer #10 R1 + NO PRICES rule (Alex). apply-shell.mjs now strips every price estimate from every page (Est. $, Valuation: ~$, the Estimated Valuation field) and fails the build if one survives. New sheet X4 (stitch/organisms/offer-composer-r1.html): photo grid, fits-their-wants first, category chips over 12 finds, Super switch, multi mode; 8 states, clickable. Opens from Put on Table in R1.' },
    { date: '2026-09-27', note: 'Agreed swap card #15 R1 (Alex: only the agreement + double confirmation matter). New sheet X3 (stitch/organisms/handover-desk-r1.html): 5 states, confirm dialog, compact chat header, phone. Swapped into R2. Map, meetup, chat peek, QR, GPS removed; meetup_spot, chat_peek, handover_steps → Skip (handover_steps merged into #15).' },
    { date: '2026-09-27', note: 'Top bar R2 (Alex: detail in tooltips, click a chip to see its organism). New states sheet X2 (stitch/organisms/topbar-r2.html): hover tooltips; streak → #03 popover (6 states), points → wallet popover, bell → notifications, account → menu; tablet, phone, phone bottom sheet. R2 is live and clickable in R1–R4. The top bar\'s "open on its own" now opens the sheet.' },
    { date: '2026-09-26', note: 'Clean-up (Alex): deleted the Deck action bar preview "Original S1 — with the key legend and Eye". Deck action bar now shows its four R1 states only.' },
    { date: '2026-09-26', note: 'Clean-up (Alex): deleted the Top bar previews "Original S1 — with search and nav" and "S5 version — 64px, 5-link nav". Top bar now shows R1 only. Stale preview files cleared.' },
    { date: '2026-09-26', note: 'Added "Missing for V6" view: pages without a design (computed), plus sheets, states, platforms and decisions no Stitch page covers yet.' },
    { date: '2026-09-26', note: 'Stitch S5 "Chat — desktop" saved (stitch/09) + R5 (stitch/10). S5 uses a different design system (green/Outfit). apply-shell.mjs generalised (optional cuts, header-height aware, token-free type); new rebuild.mjs runs the whole pipeline. 5 new organisms — 38 total. Chat → Planning.' },
    { date: '2026-09-26', note: 'Review pass started. #09 Deck action bar → R1 (Alex): legend removed, five equal buttons Undo · Pass · Put on Table · Super · Boost. New build-revisions.mjs writes organism sheets + patches page revisions.' },
    { date: '2026-09-26', note: 'Stitch S4 "My Finds & Inventory — desktop" saved (stitch/07) + R4 with the side nav (stitch/08). 6 new organisms — 33 total. tier_meter compact variant now drawn. My Items + Add a find → Planning.' },
    { date: '2026-09-26', note: 'Stitch S3 "Points & Tiers — desktop" saved (stitch/05) + R3 with the side nav (stitch/06). 5 new organisms: invite_banner, earn_rules, tier_plans, perk_store, points_ledger — 27 total. Streak + points_wallet get their S3 versions. Points, Membership, Invite → Planning.' },
    { date: '2026-09-26', note: 'Stitch S2 "Active Swaps & Offers — desktop" saved (stitch/03) + revision R2 with the side nav (stitch/04, via the new apply-shell.mjs). 9 new organisms: swaps_header, offer_card, handover_desk, meetup_spot, chat_peek, handover_steps, free_pledge (+ meta_strip, fair_trade_meter not recommended). 22 total. Matches + Offers → Planning.' },
    { date: '2026-09-26', note: 'Top bar R1 (Alex): no search — the deck is random; nav links moved into a new left side nav. New organism side_nav (13 total). Design: stitch/02-discover-desktop-r1.html.' },
    { date: '2026-09-26', note: 'Live previews: every organism is cut out of its Stitch page (build-parts.mjs → stitch/parts/) and shown on its organism page and in the new Gallery.' },
    { date: '2026-09-26', note: 'Stitch S1 "Discover Deck — desktop" saved to stitch/01-discover-desktop.html and split into 12 organisms: 2 already built on the branch, 6 extend an app component, 3 new, 1 not recommended (footer). Discover + shell moved to Planning.' },
    { date: '2026-09-26', note: 'Inventory created from client/src/router.tsx: 20 pages + the shared shell. Nothing changed for V6 yet.' },
  ],
}
