/* Generated by build-parts.mjs — do not edit. */
window.V6_PARTS = {
  "topbar": [
    {
      "label": "R2 — closed, desktop 1440",
      "file": "stitch/parts/x2-topbar.html",
      "open": "stitch/organisms/topbar-r2.html#live",
      "width": 1472,
      "vw": 1440,
      "height": 112
    },
    {
      "label": "R2 — tooltips (hover)",
      "file": "stitch/parts/x2-topbar-2.html",
      "open": "stitch/organisms/topbar-r2.html#hover",
      "width": 1472,
      "vw": 1440,
      "height": 416
    },
    {
      "label": "R2 — streak chip clicked → #03 streak",
      "file": "stitch/parts/x2-topbar-3.html",
      "open": "stitch/organisms/topbar-r2.html#streak-open",
      "width": 1472,
      "vw": 1440,
      "height": 412
    },
    {
      "label": "R2 — streak popover, other states",
      "file": "stitch/parts/x2-topbar-4.html",
      "open": "stitch/organisms/topbar-r2.html#streak-states",
      "width": 1472,
      "vw": 1440,
      "height": 670
    },
    {
      "label": "R2 — points chip clicked → wallet",
      "file": "stitch/parts/x2-topbar-5.html",
      "open": "stitch/organisms/topbar-r2.html#points-open",
      "width": 1472,
      "vw": 1440,
      "height": 532
    },
    {
      "label": "R2 — bell clicked → notifications",
      "file": "stitch/parts/x2-topbar-6.html",
      "open": "stitch/organisms/topbar-r2.html#bell-open",
      "width": 1472,
      "vw": 1440,
      "height": 452
    },
    {
      "label": "R2 — bell, nothing waiting",
      "file": "stitch/parts/x2-topbar-7.html",
      "open": "stitch/organisms/topbar-r2.html#bell-empty",
      "width": 1472,
      "vw": 1440,
      "height": 312
    },
    {
      "label": "R2 — account clicked → menu",
      "file": "stitch/parts/x2-topbar-8.html",
      "open": "stitch/organisms/topbar-r2.html#account-open",
      "width": 1472,
      "vw": 1440,
      "height": 512
    },
    {
      "label": "R2 — every chip state",
      "file": "stitch/parts/x2-topbar-9.html",
      "open": "stitch/organisms/topbar-r2.html#chips",
      "width": 1472,
      "vw": 1440,
      "height": 248
    },
    {
      "label": "R2 — tablet 1024",
      "file": "stitch/parts/x2-topbar-10.html",
      "open": "stitch/organisms/topbar-r2.html#tablet",
      "width": 1056,
      "vw": 1440,
      "height": 96
    },
    {
      "label": "R2 — phone 390",
      "file": "stitch/parts/x2-topbar-11.html",
      "open": "stitch/organisms/topbar-r2.html#phone",
      "width": 422,
      "vw": 1440,
      "height": 88
    },
    {
      "label": "R2 — phone, streak as a bottom sheet",
      "file": "stitch/parts/x2-topbar-12.html",
      "open": "stitch/organisms/topbar-r2.html#phone-sheet",
      "width": 422,
      "vw": 1440,
      "height": 752
    }
  ],
  "side_nav": [
    {
      "label": "Full — 256px, desktop",
      "file": "stitch/parts/r1-side_nav.html",
      "width": 288,
      "vw": 1440,
      "height": 792
    },
    {
      "label": "Compact — 72px rail (tablet, or collapsed)",
      "file": "stitch/parts/r1-side_nav-2.html",
      "width": 104,
      "vw": 1440,
      "height": 672
    }
  ],
  "streak": [
    {
      "label": "Wide — banner above the deck",
      "file": "stitch/parts/s1-streak.html",
      "width": 1248,
      "vw": 1440,
      "height": 134
    },
    {
      "label": "Inline — chip in the top bar",
      "file": "stitch/parts/s1-streak-2.html",
      "width": 213,
      "vw": 1440,
      "height": 62
    },
    {
      "label": "Tile — Points hero (5 of 12), S3 version",
      "file": "stitch/parts/r3-streak-3.html",
      "width": 490,
      "vw": 1440,
      "height": 278
    }
  ],
  "points_wallet": [
    {
      "label": "Inline — chip in the top bar",
      "file": "stitch/parts/s1-points_wallet.html",
      "width": 173,
      "vw": 1440,
      "height": 62
    },
    {
      "label": "Wide — Points hero (7 of 12), invite inside",
      "file": "stitch/parts/r3-points_wallet-2.html",
      "width": 679,
      "vw": 1440,
      "height": 298
    },
    {
      "label": "Inline — \"420 BP\" chip (S5)",
      "file": "stitch/parts/r5-points_wallet-3.html",
      "width": 128,
      "vw": 1440,
      "height": 60
    }
  ],
  "find_card": [
    {
      "label": "R1 — Discover at 1440 × 900 (live)",
      "file": "stitch/parts/x7-find_card.html",
      "open": "stitch/organisms/deck-stage-r1.html#fit-1440",
      "width": 752,
      "vw": 1440,
      "height": 482
    },
    {
      "label": "R1 — 1920 × 1080 (live)",
      "file": "stitch/parts/x7-find_card-2.html",
      "open": "stitch/organisms/deck-stage-r1.html#fit-1920",
      "width": 800,
      "vw": 1440,
      "height": 464
    },
    {
      "label": "R1 — 1280 × 720 (live)",
      "file": "stitch/parts/x7-find_card-3.html",
      "open": "stitch/organisms/deck-stage-r1.html#fit-1280",
      "width": 736,
      "vw": 1440,
      "height": 428
    },
    {
      "label": "R1 — phone 390 × 844 (live)",
      "file": "stitch/parts/x7-find_card-4.html",
      "open": "stitch/organisms/deck-stage-r1.html#fit-phone",
      "width": 422,
      "vw": 1440,
      "height": 876
    },
    {
      "label": "R1 — card at rest",
      "file": "stitch/parts/x7-find_card-5.html",
      "open": "stitch/organisms/deck-stage-r1.html#rest",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — details slid up",
      "file": "stitch/parts/x7-find_card-6.html",
      "open": "stitch/organisms/deck-stage-r1.html#details",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — dragging left, PASS",
      "file": "stitch/parts/x7-find_card-7.html",
      "open": "stitch/organisms/deck-stage-r1.html#drag-pass",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — dragging right, OFFER",
      "file": "stitch/parts/x7-find_card-8.html",
      "open": "stitch/organisms/deck-stage-r1.html#drag-offer",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — no match",
      "file": "stitch/parts/x7-find_card-9.html",
      "open": "stitch/organisms/deck-stage-r1.html#nomatch",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — end of the deck",
      "file": "stitch/parts/x7-find_card-10.html",
      "open": "stitch/organisms/deck-stage-r1.html#end",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "Wide — main stage (with ghost stack)",
      "file": "stitch/parts/s1-find_card-11.html",
      "width": 835,
      "vw": 1440,
      "height": 950
    }
  ],
  "owner_bar": [
    {
      "label": "R1 — one line on the photo",
      "file": "stitch/parts/x7-owner_bar.html",
      "open": "stitch/organisms/deck-stage-r1.html#rest",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — in the details panel",
      "file": "stitch/parts/x7-owner_bar-2.html",
      "open": "stitch/organisms/deck-stage-r1.html#details",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "Wide — inside the card",
      "file": "stitch/parts/s1-owner_bar-3.html",
      "width": 787,
      "vw": 1440,
      "height": 102
    },
    {
      "label": "Compact — chat header (S5)",
      "file": "stitch/parts/r5-owner_bar-4.html",
      "width": 592,
      "vw": 1440,
      "height": 155
    }
  ],
  "wants_box": [
    {
      "label": "R1 — Wants line + match pill",
      "file": "stitch/parts/x7-wants_box.html",
      "open": "stitch/organisms/deck-stage-r1.html#rest",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — no match: Wants line only",
      "file": "stitch/parts/x7-wants_box-2.html",
      "open": "stitch/organisms/deck-stage-r1.html#nomatch",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "R1 — full wish in the details panel",
      "file": "stitch/parts/x7-wants_box-3.html",
      "open": "stitch/organisms/deck-stage-r1.html#details",
      "width": 532,
      "vw": 1440,
      "height": 672
    },
    {
      "label": "Wide — inside the card",
      "file": "stitch/parts/s1-wants_box-4.html",
      "width": 787,
      "vw": 1440,
      "height": 166
    }
  ],
  "deck_actions": [
    {
      "label": "R1 — right under the card, 1440 × 900 (live)",
      "file": "stitch/parts/x7-deck_actions.html",
      "open": "stitch/organisms/deck-stage-r1.html#fit-1440",
      "width": 752,
      "vw": 1440,
      "height": 482
    },
    {
      "label": "R1 — wide, Hunter (undo locked)",
      "file": "stitch/parts/x1-deck_actions-2.html",
      "width": 768,
      "vw": 1440,
      "height": 150
    },
    {
      "label": "R1 — wide, Collector after a pass",
      "file": "stitch/parts/x1-deck_actions-3.html",
      "width": 768,
      "vw": 1440,
      "height": 150
    },
    {
      "label": "R1 — wide, not enough points",
      "file": "stitch/parts/x1-deck_actions-4.html",
      "width": 768,
      "vw": 1440,
      "height": 150
    },
    {
      "label": "R1 — compact, phone 358px",
      "file": "stitch/parts/x1-deck_actions-5.html",
      "width": 390,
      "vw": 1440,
      "height": 128
    }
  ],
  "offer_composer": [
    {
      "label": "R1 — 50 finds, nothing picked",
      "file": "stitch/parts/x4-offer_composer.html",
      "open": "stitch/organisms/offer-composer-r1.html#many",
      "width": 1032,
      "vw": 1440,
      "height": 872
    },
    {
      "label": "R1 — one picked",
      "file": "stitch/parts/x4-offer_composer-2.html",
      "open": "stitch/organisms/offer-composer-r1.html#picked",
      "width": 1032,
      "vw": 1440,
      "height": 872
    },
    {
      "label": "R1 — filtered to one category",
      "file": "stitch/parts/x4-offer_composer-3.html",
      "open": "stitch/organisms/offer-composer-r1.html#filtered",
      "width": 1032,
      "vw": 1440,
      "height": 872
    },
    {
      "label": "R1 — several at once (multi)",
      "file": "stitch/parts/x4-offer_composer-4.html",
      "open": "stitch/organisms/offer-composer-r1.html#multi",
      "width": 1032,
      "vw": 1440,
      "height": 872
    },
    {
      "label": "R1 — Super offer on",
      "file": "stitch/parts/x4-offer_composer-5.html",
      "open": "stitch/organisms/offer-composer-r1.html#super",
      "width": 1032,
      "vw": 1440,
      "height": 872
    },
    {
      "label": "R1 — Hunter, 6 finds",
      "file": "stitch/parts/x4-offer_composer-6.html",
      "open": "stitch/organisms/offer-composer-r1.html#few",
      "width": 1032,
      "vw": 1440,
      "height": 856
    },
    {
      "label": "R1 — no finds yet",
      "file": "stitch/parts/x4-offer_composer-7.html",
      "open": "stitch/organisms/offer-composer-r1.html#empty",
      "width": 1032,
      "vw": 1440,
      "height": 484
    },
    {
      "label": "R1 — phone bottom sheet",
      "file": "stitch/parts/x4-offer_composer-8.html",
      "open": "stitch/organisms/offer-composer-r1.html#phone",
      "width": 422,
      "vw": 1440,
      "height": 876
    }
  ],
  "expiring_offers": [
    {
      "label": "R1 — open",
      "file": "stitch/parts/x6-expiring_offers.html",
      "open": "stitch/organisms/discover-rail-r1.html#open",
      "width": 389,
      "vw": 1440,
      "height": 244
    },
    {
      "label": "R1 — folded to one line",
      "file": "stitch/parts/x6-expiring_offers-2.html",
      "open": "stitch/organisms/discover-rail-r1.html#folded",
      "width": 389,
      "vw": 1440,
      "height": 88
    },
    {
      "label": "R1 — nothing waiting",
      "file": "stitch/parts/x6-expiring_offers-3.html",
      "open": "stitch/organisms/discover-rail-r1.html#quiet",
      "width": 389,
      "vw": 1440,
      "height": 88
    },
    {
      "label": "Stitch S1 — tile, right rail",
      "file": "stitch/parts/s1-expiring_offers-4.html",
      "width": 422,
      "vw": 1440,
      "height": 454
    }
  ],
  "my_table": [
    {
      "label": "R1 — open",
      "file": "stitch/parts/x6-my_table.html",
      "open": "stitch/organisms/discover-rail-r1.html#open",
      "width": 389,
      "vw": 1440,
      "height": 190
    },
    {
      "label": "R1 — folded to one line",
      "file": "stitch/parts/x6-my_table-2.html",
      "open": "stitch/organisms/discover-rail-r1.html#folded",
      "width": 389,
      "vw": 1440,
      "height": 88
    },
    {
      "label": "R1 — empty table",
      "file": "stitch/parts/x6-my_table-3.html",
      "open": "stitch/organisms/discover-rail-r1.html#new",
      "width": 389,
      "vw": 1440,
      "height": 152
    },
    {
      "label": "Stitch S1 — tile, right rail",
      "file": "stitch/parts/s1-my_table-4.html",
      "width": 422,
      "vw": 1440,
      "height": 488
    }
  ],
  "tier_meter": [
    {
      "label": "R1 — open",
      "file": "stitch/parts/x6-tier_meter.html",
      "open": "stitch/organisms/discover-rail-r1.html#open",
      "width": 389,
      "vw": 1440,
      "height": 206
    },
    {
      "label": "R1 — folded to one line",
      "file": "stitch/parts/x6-tier_meter-2.html",
      "open": "stitch/organisms/discover-rail-r1.html#folded",
      "width": 389,
      "vw": 1440,
      "height": 88
    },
    {
      "label": "R1 — under the limit",
      "file": "stitch/parts/x6-tier_meter-3.html",
      "open": "stitch/organisms/discover-rail-r1.html#quiet",
      "width": 389,
      "vw": 1440,
      "height": 204
    },
    {
      "label": "R1 — Collector",
      "file": "stitch/parts/x6-tier_meter-4.html",
      "open": "stitch/organisms/discover-rail-r1.html#collector",
      "width": 389,
      "vw": 1440,
      "height": 156
    },
    {
      "label": "Stitch S1 — tile, right rail",
      "file": "stitch/parts/s1-tier_meter-5.html",
      "width": 422,
      "vw": 1440,
      "height": 327
    },
    {
      "label": "Compact — capacity bar in the My Finds header (S4)",
      "file": "stitch/parts/r4-tier_meter-6.html",
      "width": 544,
      "vw": 1440,
      "height": 110
    }
  ],
  "footer": [
    {
      "label": "Full — page footer",
      "file": "stitch/parts/s1-footer.html",
      "width": 1472,
      "vw": 1440,
      "height": 174
    },
    {
      "label": "S5 version — green, 4 columns",
      "file": "stitch/parts/s5-footer-2.html",
      "width": 1472,
      "vw": 1440,
      "height": 302
    }
  ],
  "swaps_header": [
    {
      "label": "Full — page header with tabs",
      "file": "stitch/parts/r2-swaps_header.html",
      "width": 1152,
      "vw": 1440,
      "height": 365
    }
  ],
  "offer_card": [
    {
      "label": "Wide — the most urgent offer (7 of 12)",
      "file": "stitch/parts/r2-offer_card.html",
      "width": 672,
      "vw": 1440,
      "height": 779
    },
    {
      "label": "Tile — every other offer (5 of 12)",
      "file": "stitch/parts/r2-offer_card-2.html",
      "width": 480,
      "vw": 1440,
      "height": 504
    }
  ],
  "handover_desk": [
    {
      "label": "R1 — agreed, nobody confirmed",
      "file": "stitch/parts/x3-handover_desk.html",
      "open": "stitch/organisms/handover-desk-r1.html#agreed",
      "width": 1184,
      "vw": 1440,
      "height": 439
    },
    {
      "label": "R1 — you confirmed, waiting",
      "file": "stitch/parts/x3-handover_desk-2.html",
      "open": "stitch/organisms/handover-desk-r1.html#me",
      "width": 1184,
      "vw": 1440,
      "height": 403
    },
    {
      "label": "R1 — they confirmed, your turn",
      "file": "stitch/parts/x3-handover_desk-3.html",
      "open": "stitch/organisms/handover-desk-r1.html#them",
      "width": 1184,
      "vw": 1440,
      "height": 419
    },
    {
      "label": "R1 — the confirm dialog",
      "file": "stitch/parts/x3-handover_desk-4.html",
      "open": "stitch/organisms/handover-desk-r1.html#confirm",
      "width": 1184,
      "vw": 1440,
      "height": 440
    },
    {
      "label": "R1 — both confirmed, it’s a bartefy",
      "file": "stitch/parts/x3-handover_desk-5.html",
      "open": "stitch/organisms/handover-desk-r1.html#done",
      "width": 1184,
      "vw": 1440,
      "height": 399
    },
    {
      "label": "R1 — called off",
      "file": "stitch/parts/x3-handover_desk-6.html",
      "open": "stitch/organisms/handover-desk-r1.html#off",
      "width": 1184,
      "vw": 1440,
      "height": 363
    },
    {
      "label": "R1 — compact, chat header",
      "file": "stitch/parts/x3-handover_desk-7.html",
      "open": "stitch/organisms/handover-desk-r1.html#compact",
      "width": 624,
      "vw": 1440,
      "height": 248
    },
    {
      "label": "R1 — phone 358px",
      "file": "stitch/parts/x3-handover_desk-8.html",
      "open": "stitch/organisms/handover-desk-r1.html#phone",
      "width": 390,
      "vw": 1440,
      "height": 777
    }
  ],
  "meetup_spot": [
    {
      "label": "Wide — inside the agreed card",
      "file": "stitch/parts/s2-meetup_spot.html",
      "width": 691,
      "vw": 1440,
      "height": 330
    },
    {
      "label": "Tile — \"Midpoint Zone\" (S5)",
      "file": "stitch/parts/r5-meetup_spot-2.html",
      "width": 304,
      "vw": 1440,
      "height": 380
    }
  ],
  "chat_peek": [
    {
      "label": "Wide — inside the agreed card",
      "file": "stitch/parts/s2-chat_peek.html",
      "width": 691,
      "vw": 1440,
      "height": 168
    }
  ],
  "handover_steps": [
    {
      "label": "Tile — right column of the agreed card",
      "file": "stitch/parts/s2-handover_steps.html",
      "width": 494,
      "vw": 1440,
      "height": 649
    },
    {
      "label": "Tile — \"Swap Safeguards\", 4 steps (S5)",
      "file": "stitch/parts/r5-handover_steps-2.html",
      "width": 304,
      "vw": 1440,
      "height": 460
    }
  ],
  "free_pledge": [
    {
      "label": "Wide — bottom of the page",
      "file": "stitch/parts/r2-free_pledge.html",
      "width": 1152,
      "vw": 1440,
      "height": 174
    },
    {
      "label": "Tile — \"Bartefy Trust Pledge\" (S5)",
      "file": "stitch/parts/r5-free_pledge-2.html",
      "width": 304,
      "vw": 1440,
      "height": 231
    }
  ],
  "meta_strip": [
    {
      "label": "Full — strip above the header",
      "file": "stitch/parts/r2-meta_strip.html",
      "width": 1152,
      "vw": 1440,
      "height": 86
    },
    {
      "label": "Full — S3 version (Protocol 027 / ledger synced)",
      "file": "stitch/parts/r3-meta_strip-2.html",
      "width": 1152,
      "vw": 1440,
      "height": 56
    },
    {
      "label": "S5 version — \"Borough Node #04\"",
      "file": "stitch/parts/r5-meta_strip-3.html",
      "width": 272,
      "vw": 1440,
      "height": 84
    }
  ],
  "fair_trade_meter": [
    {
      "label": "Tile — under the second offer",
      "file": "stitch/parts/r2-fair_trade_meter.html",
      "width": 480,
      "vw": 1440,
      "height": 198
    }
  ],
  "invite_banner": [
    {
      "label": "Wide — inside the balance card",
      "file": "stitch/parts/r3-invite_banner.html",
      "width": 631,
      "vw": 1440,
      "height": 120
    }
  ],
  "earn_rules": [
    {
      "label": "Wide — 5 rules in a row",
      "file": "stitch/parts/r3-earn_rules.html",
      "width": 1152,
      "vw": 1440,
      "height": 360
    }
  ],
  "tier_plans": [
    {
      "label": "Wide — Hunter, Collector, Curator",
      "file": "stitch/parts/r3-tier_plans.html",
      "width": 1152,
      "vw": 1440,
      "height": 658
    }
  ],
  "perk_store": [
    {
      "label": "Wide — 5 perks",
      "file": "stitch/parts/r3-perk_store.html",
      "width": 1152,
      "vw": 1440,
      "height": 318
    }
  ],
  "points_ledger": [
    {
      "label": "Wide — history table",
      "file": "stitch/parts/r3-points_ledger.html",
      "width": 1152,
      "vw": 1440,
      "height": 404
    }
  ],
  "items_header": [
    {
      "label": "Full — page header",
      "file": "stitch/parts/r4-items_header.html",
      "width": 1152,
      "vw": 1440,
      "height": 320
    }
  ],
  "renewal_alert": [
    {
      "label": "Wide — under the header",
      "file": "stitch/parts/r4-renewal_alert.html",
      "width": 1152,
      "vw": 1440,
      "height": 115
    }
  ],
  "inventory_filters": [
    {
      "label": "Full — chips + sort",
      "file": "stitch/parts/r4-inventory_filters.html",
      "width": 1152,
      "vw": 1440,
      "height": 64
    }
  ],
  "stall_card": [
    {
      "label": "Tile — offers pending",
      "file": "stitch/parts/r4-stall_card.html",
      "width": 390,
      "vw": 1440,
      "height": 585
    },
    {
      "label": "Tile — expiring in 3 days",
      "file": "stitch/parts/r4-stall_card-2.html",
      "width": 390,
      "vw": 1440,
      "height": 601
    },
    {
      "label": "Tile — live",
      "file": "stitch/parts/r4-stall_card-3.html",
      "width": 390,
      "vw": 1440,
      "height": 585
    },
    {
      "label": "Tile — in negotiation",
      "file": "stitch/parts/r4-stall_card-4.html",
      "width": 390,
      "vw": 1440,
      "height": 597
    }
  ],
  "stall_stats": [
    {
      "label": "Wide — bottom of the page",
      "file": "stitch/parts/r4-stall_stats.html",
      "width": 1152,
      "vw": 1440,
      "height": 280
    }
  ],
  "listing_composer": [
    {
      "label": "Dialog — opened from \"+ Put New Find on Table\"",
      "file": "stitch/parts/r4-listing_composer.html",
      "width": 932,
      "vw": 1440,
      "height": 924
    }
  ],
  "tab_bar": [
    {
      "label": "R1 — Discover",
      "file": "stitch/parts/x5-tab_bar.html",
      "open": "stitch/organisms/phone-nav-r1.html#discover",
      "width": 422,
      "vw": 1440,
      "height": 876
    },
    {
      "label": "R1 — Swaps (badge)",
      "file": "stitch/parts/x5-tab_bar-2.html",
      "open": "stitch/organisms/phone-nav-r1.html#swaps",
      "width": 422,
      "vw": 1440,
      "height": 876
    },
    {
      "label": "R1 — You sheet",
      "file": "stitch/parts/x5-tab_bar-3.html",
      "open": "stitch/organisms/phone-nav-r1.html#you",
      "width": 422,
      "vw": 1440,
      "height": 876
    },
    {
      "label": "R1 — streak chip → sheet",
      "file": "stitch/parts/x5-tab_bar-4.html",
      "open": "stitch/organisms/phone-nav-r1.html#streak",
      "width": 422,
      "vw": 1440,
      "height": 876
    },
    {
      "label": "R1 — Put on Table → sheet",
      "file": "stitch/parts/x5-tab_bar-5.html",
      "open": "stitch/organisms/phone-nav-r1.html#offer",
      "width": 422,
      "vw": 1440,
      "height": 876
    },
    {
      "label": "R1 — ＋Add → listing form",
      "file": "stitch/parts/x5-tab_bar-6.html",
      "open": "stitch/organisms/phone-nav-r1.html#add",
      "width": 422,
      "vw": 1440,
      "height": 876
    },
    {
      "label": "Alternative — Points as the fifth tab",
      "file": "stitch/parts/x5-tab_bar-7.html",
      "open": "stitch/organisms/phone-nav-r1.html#alt",
      "width": 422,
      "vw": 1440,
      "height": 876
    }
  ],
  "match_dock": [
    {
      "label": "Full — banner + both finds",
      "file": "stitch/parts/r5-match_dock.html",
      "width": 1216,
      "vw": 1440,
      "height": 210
    }
  ],
  "swap_thread_list": [
    {
      "label": "Tile — left column",
      "file": "stitch/parts/r5-swap_thread_list.html",
      "width": 304,
      "vw": 1440,
      "height": 520
    }
  ],
  "chat_thread": [
    {
      "label": "Wide — centre column (header → composer)",
      "file": "stitch/parts/r5-chat_thread.html",
      "width": 592,
      "vw": 1440,
      "height": 919
    }
  ],
  "meetup_proposal": [
    {
      "label": "Inline — inside a message",
      "file": "stitch/parts/r5-meetup_proposal.html",
      "width": 468,
      "vw": 1440,
      "height": 264
    }
  ],
  "chat_composer": [
    {
      "label": "Wide — bottom of the thread",
      "file": "stitch/parts/r5-chat_composer.html",
      "width": 592,
      "vw": 1440,
      "height": 168
    }
  ]
}
